### ISSUE TITLE
Proper multi-library support

### ISSUE THREAD

**Issue by jgoguen** [eeston/Jello#2]
I have three music libraries, which Jello combines into one. For what they are, this doesn't make sense for me. I have:

- One library for music, which I want to be able to see all songs for. Usually I will start by shuffling all songs but occasionally need to pick a specific song and then shuffle the rest. If I get to the end of the shuffled list, I expect it to reshuffle and start again.
- One library for full-length concerts. Normally when I go to this library I'm looking to pick a specific entry and they're all over an hour long, so this is the only library where the current Jello layout works for me. It would be nice to shuffle to other concerts once the current one is  done, but when I come to this library I'm usually looking for something very specific before moving on to something else entirely so it's also nice to be able to queue one or two and end once the queue is empty.
- One library for sleep stories. For this library, I always want to queue up a specific story (maybe two) and then end playback once the queued stories are complete. Whether that means tapping a story or long-pressing to add to queue isn't important, as long as I can view all stories, queue up one or more, and stop playback once the queue is empty.

The Apple Music solution of going to iTunes and flagging individual songs as "exclude from shuffle" would be an acceptable workaround, but obviously not preferable.

**Comment by eeston** [comment]
Quick solution in 0.0.44. You should be able to select a library of choice from the settings page
