### ISSUE TITLE
UI bug: long titles move art out of alignment

### ISSUE THREAD

**Issue by jgoguen** [eeston/Jello#5]
A long song name isn’t properly wrapped, causing the art square to be moved out of alignment.

![IMG_2121](https://github.com/eeston/Jello/assets/189497/6a4b9bc7-537a-4c2e-8562-f2d39315c1e1)

iOS 17.3.1 on iPhone 15 Pro Max
Jello 0.0.36

**Comment by eeston** [comment]
Fix available in 0.0.38

**Comment by jgoguen** [comment]
That fixed it!
